/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Hamberger(props) {
  const { nodes, materials } = useGLTF('./hamburger-draco.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        name="bottomBun"
        castShadow
        receiveShadow
        geometry={nodes.bottomBun.geometry}
        material={materials.BunMaterial}
        position={[0, -1.25, 0]}
      />
      <mesh
        name="meat"
        castShadow
        receiveShadow
        geometry={nodes.meat.geometry}
        material={materials.SteakMaterial}
        position={[0, 1.817, 0]}
      />
      <mesh
        name="cheese"
        castShadow
        receiveShadow
        geometry={nodes.cheese.geometry}
        material={materials.CheeseMaterial}
        position={[0, 2.04, 0]}
      />
      <mesh
        name="topBun"
        castShadow
        receiveShadow
        geometry={nodes.topBun.geometry}
        material={materials.BunMaterial}
        position={[0, 1.771, 0]}
      />
    </group>
  )
}

useGLTF.preload('./hamburger-draco.glb')
